version: '3.5'

services:
  postgres_db:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - ./data/postgres:/data
    env_file:
      - ".env"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
      PGDATA: "/var/lib/postgresql/data"
    networks:
      - postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest
    env_file:
      - .env
    environment:
      - PORT=${HTTP_SERVER_PORT}
    ports:
      - '${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}'
    depends_on:
      - postgres_db
    links:
      - postgres_db:postgres_db
    volumes:
      - ./src:/app/src
      - /app/node_modules
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    env_file:
      - .env.development
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - '${PGADMIN_DEFAULT_PORT}:80'
    depends_on:
      - postgres_db
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
